on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-push:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
      - run: npm test 
        env:
          TESTCONTAINERS_RYUK_DISABLED: true